from enum import StrEnum


class EventType(StrEnum):
    SCHEDULE_EVENT = "SCHEDULE_EVENT"
    CHANGE_KEY = "CHANGE_KEY"
    GENERATE_REPORT = "GENERATE_REPORT"


class RPCPayloadType(StrEnum):
    GET_INTERVIEW_DETAILS = "GET_INTERVIEW_DETAILS"
    GET_USER_RESUME = "GET_USER_RESUME"
