from enum import StrEnum


class EventType(StrEnum):
    INTERVIEW_STARTED = "INTERVIEW_STARTED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    SCHEDULE_EVENT = "SCHEDULE_EVENT"
    CHANGE_KEY = "CHANGE_KEY"
    GENERATE_REPORT = "GENERATE_REPORT"
    INTERVIEW_DETAILS = "INTERVIEW_DETAILS"


class RPCPayloadType(StrEnum):
    GET_INTERVIEW_DETAILS = "GET_INTERVIEW_DETAILS"
    GET_USER_RESUME = "GET_USER_RESUME"
